version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    expose:
      - "${PORT}"
    links:
      - "db:api"
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGPORT: ${PGPORT}
    ports:
      - ${PGPORT}
    expose:
      - ${PGPORT}
    volumes:
      - data:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes: 
 data: {}
